# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rdv < Formula
  desc "Interactive dev‑env config manager"
  homepage "https://github.com/yonasyiheyis/rdv"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yonasyiheyis/rdv/releases/download/v0.1.0/rdv_0.1.0_darwin_amd64.tar.gz"
      sha256 "ef9a0c10ceaf5da13d1ebd22d5856785dcad59b1eab650c10b37bbf631b71fe8"

      def install
        bin.install "rdv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yonasyiheyis/rdv/releases/download/v0.1.0/rdv_0.1.0_darwin_arm64.tar.gz"
      sha256 "db5fe37d61c1f9cd4d9ce66ca8cdfbff1d53dac468c9a88a5b377a47fa0f77c5"

      def install
        bin.install "rdv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/yonasyiheyis/rdv/releases/download/v0.1.0/rdv_0.1.0_linux_amd64.tar.gz"
      sha256 "394a94fa8753d392cf8ec17701cc9b168070d858b0313a559f8c673b16139b66"
      def install
        bin.install "rdv"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/yonasyiheyis/rdv/releases/download/v0.1.0/rdv_0.1.0_linux_arm64.tar.gz"
      sha256 "2ff51a135f0b792e6947a83cbd14ebd7d85a7aed99cf58463909b7240ffdc442"
      def install
        bin.install "rdv"
      end
    end
  end

  def caveats
    <<~EOS
      After installation, enable shell completion:
        rdv completion zsh > $(brew --prefix)/share/zsh/site-functions/_rdv
    EOS
  end

  test do
    rdv --version
  end
end
