# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rdv < Formula
  desc "Interactive dev‑env config manager"
  homepage "https://github.com/yonasyiheyis/rdv"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yonasyiheyis/rdv/releases/download/v0.1.1/rdv_0.1.1_darwin_amd64.tar.gz"
      sha256 "f628b578788ec8384002fd0fbf9013ea45b5f705da03540cf52d4032ae114d89"

      def install
        bin.install "rdv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yonasyiheyis/rdv/releases/download/v0.1.1/rdv_0.1.1_darwin_arm64.tar.gz"
      sha256 "5e4a54654add3efffa01e5faed9e3f1882e45986e2774df972844af37c6b3c01"

      def install
        bin.install "rdv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/yonasyiheyis/rdv/releases/download/v0.1.1/rdv_0.1.1_linux_amd64.tar.gz"
      sha256 "330702f7d25ba5d774d35e0de599e6e635e6a550a9de9fcafcb8831e49dd88e2"
      def install
        bin.install "rdv"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/yonasyiheyis/rdv/releases/download/v0.1.1/rdv_0.1.1_linux_arm64.tar.gz"
      sha256 "cf5bb909209f18bfe8c4fde1fac85aebe75ddbf45658118c6806aee9cc7c1ada"
      def install
        bin.install "rdv"
      end
    end
  end

  def caveats
    <<~EOS
      After installation, enable shell completion:
        rdv completion zsh > $(brew --prefix)/share/zsh/site-functions/_rdv
    EOS
  end

  test do
    rdv --version
  end
end
