# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rdv < Formula
  desc "Interactive dev‑env config manager"
  homepage "https://github.com/yonasyiheyis/rdv"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yonasyiheyis/rdv/releases/download/v0.5.0/rdv_0.5.0_darwin_amd64.tar.gz"
      sha256 "27adc6f36af53f9d129f8ea9cf8e27caefd9c066bf83048c03e4aa9dfb1f0229"

      def install
        bin.install "rdv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yonasyiheyis/rdv/releases/download/v0.5.0/rdv_0.5.0_darwin_arm64.tar.gz"
      sha256 "88251f656548a0c92a8f9d82b62d7d340e98658709897b2634d500bec7d7f728"

      def install
        bin.install "rdv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/yonasyiheyis/rdv/releases/download/v0.5.0/rdv_0.5.0_linux_amd64.tar.gz"
      sha256 "7d67d94567d9a4b1b0d6780a6f81b2bc34cc1e272b87a6d76bfc70475fbc063d"
      def install
        bin.install "rdv"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/yonasyiheyis/rdv/releases/download/v0.5.0/rdv_0.5.0_linux_arm64.tar.gz"
      sha256 "893a75055fc89cd1a32fcb3efc1dd8e1fd594693d69dfccdc9e593a9ad8c269f"
      def install
        bin.install "rdv"
      end
    end
  end

  def caveats
    <<~EOS
      After installation, enable shell completion:
        rdv completion zsh > $(brew --prefix)/share/zsh/site-functions/_rdv
    EOS
  end

  test do
    rdv --version
  end
end
